services:
  directv-portal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: directv-portal
    image: sdtorresl/directv-portal:0.0.1
    ports:
      - "80:80"
    environment:
      - API_BASE_URL=http://localhost:3000
      - JWT_USER=user
      - JWT_PASSWORD=password
